repos:
-   repo: https://github.com/psf/black.git
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: mixed-line-ending

- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.7.5
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear==18.8.0; python_version >= '3.7'"]
